-- ============================================================
-- [RENAME] iplBlockerGroups
-- Purpose: Each entry is a named group of .ymap IPL blocker
--          files to RequestIpl() at startup, before any
--          resource-specific removal pass runs.
-- ============================================================

local iplBlockerGroups = {
    -- [RENAME] Hornys blocker group
    {
        name = "Hornys",
        ymap = {
            "gabz_ipl_hornys_blocker",       -- main blocker ymap
            "gabz_ipl_hornys_blocker_occl",  -- occlusion blocker ymap
        },
    },

    -- [RENAME] Mirrorpark1 blocker group
    {
        name = "Mirrorpark1",
        ymap = {
            "gabz_ipl_mirrorpark1_blocker",       -- main blocker ymap
            "gabz_ipl_mirrorpark1_blocker_occl",  -- occlusion blocker ymap
        },
    },

    -- [RENAME] Catcafe blocker group
    {
        name = "Catcafe",
        ymap = {
            "gabz_ipl_catcafe_blocker",  -- main blocker ymap
        },
    },

    -- [RENAME] Triads blocker group
    {
        name = "Triads",
        ymap = {
            "gabz_ipl_triads_blocker",  -- main blocker ymap
        },
    },

    -- [RENAME] Diner (Pizzeria) blocker group
    {
        name = "Diner",
        ymap = {
            "gabz_ipl_diner_ext",   -- exterior IPL
            "gabz_ipl_diner_lod",   -- LOD IPL
            "gabz_ipl_diner_slod",  -- SLOD (super LOD) IPL
        },
    },

    -- [RENAME] Ottos blocker group
    {
        name = "Ottos",
        ymap = {
            "gabz_ipl_otto_ext",   -- exterior IPL
            "gabz_ipl_otto_lod",   -- LOD IPL
            "gabz_ipl_otto_slod",  -- SLOD IPL
        },
    },
}

-- ============================================================
-- [RENAME] conditionalIplGroups
-- Purpose: IPL groups that are only loaded/removed conditionally
--          depending on which gabz resources are running.
--          Specifically handles the vanilla 247 vs gabz 247
--          variant swap for Otto's storefront.
-- ============================================================

local conditionalIplGroups = {
    -- [RENAME] Ottos247Entry — vanilla 247 blocker for Otto's
    -- Loaded when cfx-gabz-ottos is present but cfx-gabz-247 is not
    {
        name = "Ottos247",
        ymap = {
            "gabz_ipl_vanilla_247_otto_milo",  -- vanilla 247 milo IPL
            "gabz_ipl_vanilla_247_otto_lod",   -- vanilla 247 LOD IPL
        },
    },

    -- [RENAME] OttosGabz247Entry — gabz 247 blocker for Otto's
    -- Loaded when BOTH cfx-gabz-ottos AND cfx-gabz-247 are present
    {
        name = "OttosGabz247",
        ymap = {
            "gabz_247_ipl_otto_milo",  -- gabz 247 milo IPL
            "gabz_247_ipl_otto_lod",   -- gabz 247 LOD IPL
        },
    },
}

-- ============================================================
-- [RENAME] staticEmitterDisables
-- Purpose: A list of ambient static sound emitters that must be
--          disabled because the gabz interior replacements remove
--          the geometry those emitters are attached to.
--          Each entry has:
--            associatedInterior — human label for the location
--            generatedName      — the internal emitter name as
--                                 generated by the audio system
--            actualName         — override name if the generated
--                                 name is wrong; nil = use generated
-- ============================================================

local staticEmitterDisables = {
    -- [RENAME] pearlsEmitterEntry
    {
        associatedInterior = "Pearls",
        generatedName      = "se_racing_ferris_utopia",
        actualName         = nil,  -- use generatedName
    },

    -- [RENAME] burgershotEmitterEntry
    {
        associatedInterior = "Burgershot",
        generatedName      = "se_restaurants_fucker_gasdoor_bearsy",
        actualName         = nil,  -- use generatedName
    },
}

-- ============================================================
-- [NATIVE] [FRAMEWORK] CreateThread — FiveM client thread
-- Runs once on resource start.
-- ============================================================

--[[
  Function: threadMain()
  Purpose:  Entry point. Runs at resource start inside a FiveM thread.
            1. Disables all static ambient emitters in staticEmitterDisables.
            2. RequestIpl() for every ymap in every iplBlockerGroups entry.
            3. Enumerates all currently started resources.
            4. For each known gabz resource that is running, removes the
               corresponding blocker IPLs (because the gabz resource
               supplies its own geometry and does not need the blockers).
            5. Handles the Ottos / 247 conditional swap via
               conditional_ipl_check().
  Params:   none
  Returns:  none
--]]

CreateThread(function()

    -- [RENAME] isOttosActive — set true if cfx-gabz-ottos is found running,
    -- used later to decide whether the 247 conditional swap applies.
    local isOttosActive = false

    -- --------------------------------------------------------
    -- Step 1: Disable static ambient sound emitters.
    -- The decompiler emitted a redundant double-check for
    -- actualName; the intent is simply: use actualName when set,
    -- otherwise fall back to generatedName.
    -- --------------------------------------------------------
    for _, emitterEntry in pairs(staticEmitterDisables) do
        local emitterName

        if emitterEntry.actualName then
            -- [DECODE] Decompiler produced a duplicate nil-check here;
            -- both branches resolve to the same field. Simplified below.
            emitterName = emitterEntry.actualName
        else
            emitterName = emitterEntry.generatedName
        end

        -- [NATIVE] SetStaticEmitterEnabled — disables the named ambient
        -- sound emitter in the world so it no longer plays audio.
        SetStaticEmitterEnabled(emitterName, false) -- [NATIVE]
    end

    -- --------------------------------------------------------
    -- Step 2: RequestIpl for every blocker group entry.
    -- This loads all blocker ymaps so vanilla map geometry is
    -- suppressed in areas gabz resources will replace.
    -- --------------------------------------------------------
    for _, blockerGroup in ipairs(iplBlockerGroups) do
        for _, ymapName in ipairs(blockerGroup.ymap) do
            RequestIpl(ymapName) -- [NATIVE]
        end
    end

    -- --------------------------------------------------------
    -- Step 3: Collect all currently started resources into a
    -- list so we can check which gabz resources are active.
    -- --------------------------------------------------------

    -- [RENAME] startedResources — list of resource name strings
    local startedResources = {}

    for i = 0, GetNumResources() do -- [NATIVE] GetNumResources
        local resourceName = GetResourceByFindIndex(i) -- [NATIVE]

        if resourceName then
            if GetResourceState(resourceName) == "started" then -- [NATIVE]
                table.insert(startedResources, resourceName)
            end
        end
    end

    -- --------------------------------------------------------
    -- Step 4: For each known gabz resource that is running,
    -- remove its corresponding blocker IPLs — the gabz resource
    -- itself provides the correct geometry, so the blockers are
    -- no longer needed and would cause visual conflicts.
    -- --------------------------------------------------------
    for _, resourceName in ipairs(startedResources) do

        if resourceName == "cfx-gabz-hornys" then
            disable_IplbyName("Hornys")
        end

        if resourceName == "cfx-gabz-mirrorpark1" then
            disable_IplbyName("Mirrorpark1")
        end

        if resourceName == "cfx-gabz-catcafe" then
            disable_IplbyName("Catcafe")
        end

        if resourceName == "cfx-gabz-triads" then
            disable_IplbyName("Triads")
        end

        -- [RENAME] cfx-gabz-pizzeria maps to the "Diner" group internally
        if resourceName == "cfx-gabz-pizzeria" then
            disable_IplbyName("Diner")
        end

        if resourceName == "cfx-gabz-ottos" then
            -- Remove the Ottos main blocker group
            disable_IplbyName("Ottos")

            -- Load the vanilla-247 Otto blocker as a starting point;
            -- conditional_ipl_check will swap it for the gabz-247 variant
            -- if cfx-gabz-247 is also running.
            enable_conditional_IplbyName("Ottos247")

            isOttosActive = true
        end

    end

    -- --------------------------------------------------------
    -- Step 5: Run the conditional 247 swap check.
    -- If isOttosActive is true AND cfx-gabz-247 is in the
    -- started resource list, swap Ottos247 → OttosGabz247.
    -- --------------------------------------------------------
    conditional_ipl_check(startedResources, isOttosActive) -- [EVENT-adjacent] conditional dispatch

end)

-- ============================================================
--[[
  Function: conditional_ipl_check(startedResources, isOttosActive)
  Purpose:  Checks whether cfx-gabz-247 is running AND Otto's
            gabz resource was also detected. If both are true,
            removes the vanilla-247 Otto blocker (Ottos247) and
            loads the gabz-247 variant (OttosGabz247) instead.
  Params:   startedResources (table)  — list of started resource name strings
            isOttosActive    (boolean) — whether cfx-gabz-ottos was found running
  Returns:  none
--]]
-- ============================================================

function conditional_ipl_check(startedResources, isOttosActive)

    for _, resourceName in ipairs(startedResources) do

        if resourceName == "cfx-gabz-247" and isOttosActive then
            -- Swap: remove the vanilla-247 Otto conditional blocker...
            disable_conditional_IplbyName("Ottos247")

            -- ...and load the gabz-247 variant instead.
            enable_conditional_IplbyName("OttosGabz247")
        end

    end

end

-- ============================================================
--[[
  Function: disable_IplbyName(groupName)
  Purpose:  Finds the named group inside iplBlockerGroups and
            calls RemoveIpl() on every ymap in that group.
            Used to unload standard blocker IPLs when the
            corresponding gabz resource is active.
  Params:   groupName (string) — the .name field to match in iplBlockerGroups
  Returns:  none
--]]
-- ============================================================

function disable_IplbyName(groupName)

    for _, blockerGroup in ipairs(iplBlockerGroups) do
        if blockerGroup.name == groupName then
            for _, ymapName in ipairs(blockerGroup.ymap) do
                RemoveIpl(ymapName) -- [NATIVE]
            end
        end
    end

end

-- ============================================================
--[[
  Function: disable_conditional_IplbyName(groupName)
  Purpose:  Finds the named group inside conditionalIplGroups
            and calls RemoveIpl() on every ymap in that group.
            Used to unload conditional IPLs during the 247 swap.
  Params:   groupName (string) — the .name field to match in conditionalIplGroups
  Returns:  none
--]]
-- ============================================================

function disable_conditional_IplbyName(groupName)

    for _, conditionalGroup in ipairs(conditionalIplGroups) do
        if conditionalGroup.name == groupName then
            for _, ymapName in ipairs(conditionalGroup.ymap) do
                RemoveIpl(ymapName) -- [NATIVE]
            end
        end
    end

end

-- ============================================================
--[[
  Function: enable_conditional_IplbyName(groupName)
  Purpose:  Finds the named group inside conditionalIplGroups
            and calls RequestIpl() on every ymap in that group.
            Used to load conditional IPLs (e.g. the correct
            247 storefront variant for Otto's).
  Params:   groupName (string) — the .name field to match in conditionalIplGroups
  Returns:  none
--]]
-- ============================================================

function enable_conditional_IplbyName(groupName)

    for _, conditionalGroup in ipairs(conditionalIplGroups) do
        if conditionalGroup.name == groupName then
            for _, ymapName in ipairs(conditionalGroup.ymap) do
                RequestIpl(ymapName) -- [NATIVE]
            end
        end
    end

end